### PR TITLE
Add more event filter operators

### PR DESCRIPTION
**Pull request by nicolewhite**

### CODE REVIEW

**Review by adamnolte — DISMISSED** [review]
Just realized we have equals and not equals but then it's equal singlular for the new ones. Not sure what's standard

**Comment by nicolewhite** [comment]
hmm true, want me to make the new ones `LESS_THAN_OR_EQUALS` and `GREATER_THAN_OR_EQUALS`?

**Comment by nicolewhite** [comment]
or switch `EQUALS` to `EQUAL` and `NOT_EQUALS` to `NOT_EQUAL`

**Comment by nicolewhite** [comment]
ClickHouse appears to use "equals" for everything: https://clickhouse.com/docs/en/sql-reference/functions/comparison-functions

**Comment by adamnolte** [comment]
I say EQUALS plural in my head, but i'm fine with either but i think we should be consistent

**Review by adamnolte — APPROVED** [review]

**Pull request merged**
